### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by DonKaye** [malinkang/weread_to_notion#13]
Run python weread.py "***" "***" "***" 
Traceback (most recent call last):
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 389, in <module>
    session.get(WEREAD_URL)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/sessions.py", line 717, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/cookies.py", line [13](https://github.com/DonKaye/weread_to_notion/actions/runs/4910504955/jobs/8767733994#step:5:14)7, in extract_cookies_to_jar
    jar.extract_cookies(res, req)
AttributeError: 'NoneType' object has no attribute 'extract_cookies'
Error: Process completed with exit code 1.

**Comment by malinkang** [comment]
cookie设置的有问题

**Comment by DonKaye** [comment]
搞定了，Mac 用Edge浏览器复制出来的cookies 试了很多次都是上面的提示，用Chrome复制，再试就成功了
