### ISSUE TITLE
报错，在函数内部更改全局变量

### ISSUE THREAD

**Issue by protea-ban** [malinkang/weread_to_notion#18]
```
Traceback (most recent call last):
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 409, in <module>
    isbn,rating = get_bookinfo(bookId)
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 67, in get_bookinfo
    return (isbn, rating)
UnboundLocalError: local variable 'rating' referenced before assignment
Error: Process completed with exit code 1.
```
报错如上，google 了一下，意思是在函数内部更改全局变量导致的错误，需要在函数内部做个声明 `global rating`，不知是否可行。

但在 notion 有记录且仅有一条。

如果大佬更新了代码，我们需要重新 fork ，重新走流程吗？

感谢！

**Comment by malinkang** [comment]
重新复制模版和fork代码试试

**Comment by protea-ban** [comment]
还是不行，同样的错误，而且只有一条记录，还是那本书，记录中 Rating 是有值的，像是调第二遍的时候报错了？

**Comment by protea-ban** [comment]
还是不行，等有空了我在本地运行试试吧，谢谢大佬！
