### ISSUE TITLE
报错，请求参数有问题？

### ISSUE THREAD

**Issue by SuFu123** [malinkang/weread_to_notion#19]
已经根据步骤正确设置了NOTION_TOKEN、NOTION_DATABASE_ID、WEREAD_COOKIE，但在运行时出现如下报错：
Traceback (most recent call last):
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 345, in <module>
    session.get(WEREAD_URL)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/sessions.py", line 719, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/cookies.py", line [13](https://github.com/SuFu123/weread_to_notion/actions/runs/5103233905/jobs/9173323034#step:5:14)7, in extract_cookies_to_jar
    jar.extract_cookies(res, req)
AttributeError: 'NoneType' object has no attribute 'extract_cookies'
Error: Process completed with exit code 1.
看上去似乎是因为Cookie传参有问题？

**Comment by SuFu123** [comment]
改用Google就解决了lol
