### ISSUE TITLE
一直同步错误，只同步了几本书。UnboundLocalError: local variable 'newRating' referenced before assignment

### ISSUE THREAD

**Issue by zxwtmac** [malinkang/weread_to_notion#25]
报错代码如下，谢谢
Traceback (most recent call last):
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 409, in <module>
    isbn,rating = get_bookinfo(bookId)
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 67, in get_bookinfo
    return (isbn, newRating)
UnboundLocalError: local variable 'newRating' referenced before assignment
Error: Process completed with exit code 1.

**Comment by malinkang** [comment]
可以把你的cookie和datebaseid发我，我帮你debug排查下。

**Comment by changingwang** [comment]
同样的问题，请问解决了了吗

[33](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:33)
Run python weread.py "***" "***" "***" 
[43](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:44)
##[debug]/usr/bin/bash -e /home/runner/work/_temp/6be25f86-c2f1-4654-b984-4a2822f56f4a.sh
[44](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:45)
Traceback (most recent call last):
[45](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:46)
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 409, in <module>
[46](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:47)
    isbn,rating = get_bookinfo(bookId)
[47](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:48)
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 67, in get_bookinfo
[48](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:49)
    return (isbn, newRating)
[49](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:50)
UnboundLocalError: local variable 'newRating' referenced before assignment
[50](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:51)
Error: Process completed with exit code 1.
[51](https://github.com/changingwang/weread_to_notion/actions/runs/6290303970/job/17082574995#step:5:52)

**Comment by changingwang** [comment]
我把代码里跟rating相关的内容都删除了，然后重新运行，好像又能同步了。。。

**Comment by zxwtmac** [comment]
我是删除重新设置一遍，就可以同步了

**Comment by changingwang** [comment]
我删除重新设置试试，上午查了一下，除了这个问题好像还有近期notion api的问题，总是报502，https://github.com/makenotion/notion-sdk-js/issues/172
