### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Rorschachina** [malinkang/weread_to_notion#3]
错误信息：
Traceback (most recent call last):
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 380, in <module>
    bookmark_list = sorted(bookmark_list, key=lambda x: (
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 381, in <lambda>
    x.get("chapterUid", 1), 0 if x.get("range") == "" else int(x.get("range").split("-")[0])))
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Rorschachina** [comment]
改成0 if not x.get("range") else int(x.get("range").split("-")[0])))应该就可以

**Comment by malinkang** [comment]
已修复
