### ISSUE TITLE
提示报错，请问有没有能告知下处理方向？建立了connect，确定三个参数填入没有问题

### ISSUE THREAD

**Issue by groundwater-modeling** [malinkang/weread_to_notion#5]
报错：
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/notion_client/client.py", line 118, in _parse_response
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api.notion.com/v1/databases/***/query'
For more information check: https://httpstatuses.com/404

notion_client.errors.APIResponseError: Could not find database with ID: *******my_id******. Make sure the relevant pages and databases are shared with your integration.

**Comment by groundwater-modeling** [comment]
文档必须要邀请集成到页面，不然没有权限写入
